/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VBusItemAdaptor -a v_busitem_adaptor.h:v_busitem_adaptor.cpp com.victron.busitem.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef V_BUSITEM_ADAPTOR_H_1440011482
#define V_BUSITEM_ADAPTOR_H_1440011482

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.victronenergy.BusItem
 */
class VBusItemAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.victronenergy.BusItem")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.victronenergy.BusItem\">\n"
"    <method name=\"GetValue\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"GetText\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"SetValue\">\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"GetMin\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"GetMax\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"SetDefault\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"GetDefault\">\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <property access=\"readwrite\" type=\"v\" name=\"Value\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Text\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"changes\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    VBusItemAdaptor(QObject *parent);
    virtual ~VBusItemAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString Text READ text)
    QString text() const;

    Q_PROPERTY(QDBusVariant Value READ value WRITE setValue)
    QDBusVariant value() const;
    void setValue(const QDBusVariant &value);

public Q_SLOTS: // METHODS
    QDBusVariant GetDefault();
    QDBusVariant GetMax();
    QDBusVariant GetMin();
    QString GetText();
    QDBusVariant GetValue();
    int SetDefault();
    int SetValue(const QDBusVariant &value);
Q_SIGNALS: // SIGNALS
    void PropertiesChanged(const QVariantMap &changes);
};

#endif
